import React, { useState } from 'react';
import {
  X,
  Code2,
  Terminal,
  Play,
  Copy,
  Check,
  Sparkles,
  Layers,
  Cpu,
  FileCode,
  Zap,
  CheckCircle2,
  RefreshCw,
  Search,
  ExternalLink,
  BookOpen,
} from 'lucide-react';
import { ContrastMode, ProgrammingLanguage, CodeTemplateItem } from '../types';
import {
  PROGRAMMING_LANGUAGES_LIST,
  INITIAL_CODE_TEMPLATES,
  explainCodeSnippet,
} from '../utils/codeAssistantData';

interface CodeAssistantModalProps {
  isOpen: boolean;
  contrastMode?: ContrastMode;
  onClose: () => void;
  onLogVoiceCommand?: (command: string, category: any, details?: string, source?: any) => void;
}

export const CodeAssistantModal: React.FC<CodeAssistantModalProps> = ({
  isOpen,
  contrastMode = 'cosmic',
  onClose,
  onLogVoiceCommand,
}) => {
  const [selectedLanguage, setSelectedLanguage] = useState<ProgrammingLanguage>('typescript');
  const [activeTab, setActiveTab] = useState<'templates' | 'sandbox' | 'explainer' | 'generator'>('templates');
  const [selectedTemplate, setSelectedTemplate] = useState<CodeTemplateItem>(INITIAL_CODE_TEMPLATES[0]);
  const [searchQuery, setSearchQuery] = useState('');
  const [copiedCode, setCopiedCode] = useState(false);

  // Sandbox State
  const [sandboxCode, setSandboxCode] = useState<string>(INITIAL_CODE_TEMPLATES[0].codeSnippet);
  const [sandboxOutput, setSandboxOutput] = useState<string>('Ready to execute code snippet...');
  const [isExecuting, setIsExecuting] = useState<boolean>(false);

  // Explainer State
  const [explainerInput, setExplainerInput] = useState<string>(INITIAL_CODE_TEMPLATES[2].codeSnippet);
  const [explanationReport, setExplanationReport] = useState(() => explainCodeSnippet(INITIAL_CODE_TEMPLATES[2].codeSnippet, 'typescript'));

  // Generator State
  const [generatorPrompt, setGeneratorPrompt] = useState<string>('Create a React hook for tracking user window resize dimensions with throttling');
  const [generatedCode, setGeneratedCode] = useState<string>('');

  const isTrueBlack = contrastMode === 'true-black';

  if (!isOpen) return null;

  const filteredTemplates = INITIAL_CODE_TEMPLATES.filter((t) => {
    const matchesLang = selectedLanguage === 'typescript' || t.language === selectedLanguage;
    const matchesSearch =
      t.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.tags.some((tag) => tag.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesLang && matchesSearch;
  });

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleRunSandbox = () => {
    setIsExecuting(true);
    setSandboxOutput('Compiling and running in secure browser context...');

    setTimeout(() => {
      try {
        if (selectedLanguage === 'javascript' || selectedLanguage === 'typescript') {
          // Safe evaluation simulation
          setSandboxOutput(`[Execution Success ⚡ 14ms]\n> TypeScript v5.4 TypeCheck: OK (0 errors)\n> Output:\n[ 0, 1 ]\n// Code executed cleanly with optimal memory footprint.`);
        } else if (selectedLanguage === 'python') {
          setSandboxOutput(`[Python 3.12 Runtime 🐍]\n> Scraped 2 pages successfully:\n[ {'url': 'https://news.ycombinator.com', 'status': 200, 'title': 'Hacker News'} ]`);
        } else if (selectedLanguage === 'sql') {
          setSandboxOutput(`[PostgreSQL Query Output 🗄️]\n| order_date | daily_revenue | cumulative_revenue | rolling_7day_avg |\n| 2026-09-01 | $14,250.00    | $142,500.00        | $12,800.00       |`);
        } else {
          setSandboxOutput(`[Sandbox Execution Success]\n> Process returned code 0 (0.012s)`);
        }
      } catch (err: any) {
        setSandboxOutput(`[Runtime Error]: ${err.message}`);
      }
      setIsExecuting(false);
    }, 450);
  };

  const handleExplainCode = () => {
    const report = explainCodeSnippet(explainerInput, selectedLanguage);
    setExplanationReport(report);
  };

  const handleGenerateCode = () => {
    const sampleSnippet = `import { useState, useEffect } from 'react';

/**
 * useWindowSize custom React hook
 * Generated by Myraa AI Code Assistant
 */
export function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: typeof window !== 'undefined' ? window.innerWidth : 1200,
    height: typeof window !== 'undefined' ? window.innerHeight : 800,
  });

  useEffect(() => {
    let timeoutId: any = null;

    const handleResize = () => {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }, 100);
    };

    window.addEventListener('resize', handleResize);
    return () => {
      window.removeEventListener('resize', handleResize);
      clearTimeout(timeoutId);
    };
  }, []);

  return windowSize;
}`;
    setGeneratedCode(sampleSnippet);
    if (onLogVoiceCommand) {
      onLogVoiceCommand(`Generate code: ${generatorPrompt}`, 'system', 'Generated TypeScript React hook');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/80 backdrop-blur-md animate-fade-in">
      <div
        className={`relative w-full max-w-5xl max-h-[90vh] flex flex-col rounded-2xl border shadow-2xl overflow-hidden ${
          isTrueBlack
            ? 'bg-black border-zinc-700 text-white'
            : 'bg-zinc-950/95 border-cyan-500/30 text-zinc-100'
        }`}
      >
        {/* Top Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-zinc-800/80 bg-zinc-900/50">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Code2 className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold tracking-tight text-white">
                  AI Code Assistant & Dev Studio
                </h2>
                <span className="px-2 py-0.5 text-[11px] font-semibold rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 font-mono">
                  Multi-Lang v2.4
                </span>
              </div>
              <p className="text-xs text-zinc-400">
                Generate production-ready code, explain complex algorithms, debug errors, and run live snippets
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-zinc-400 hover:text-white hover:bg-zinc-800/60 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Language Selector Ribbon */}
        <div className="flex items-center gap-2 px-5 py-2.5 overflow-x-auto border-b border-zinc-800 bg-zinc-900/30 no-scrollbar">
          <span className="text-xs text-zinc-400 whitespace-nowrap font-medium flex items-center gap-1.5 mr-1">
            <Terminal className="w-3.5 h-3.5 text-cyan-400" /> Language:
          </span>
          {PROGRAMMING_LANGUAGES_LIST.map((lang) => {
            const isSelected = selectedLanguage === lang.id;
            return (
              <button
                key={lang.id}
                onClick={() => {
                  setSelectedLanguage(lang.id);
                  const matching = INITIAL_CODE_TEMPLATES.find((t) => t.language === lang.id);
                  if (matching) {
                    setSelectedTemplate(matching);
                    setSandboxCode(matching.codeSnippet);
                  }
                }}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center gap-1.5 ${
                  isSelected
                    ? 'bg-cyan-500 text-black shadow-md shadow-cyan-500/20 font-bold scale-102'
                    : 'bg-zinc-800/60 text-zinc-300 hover:bg-zinc-800 hover:text-white border border-zinc-700/50'
                }`}
              >
                <span>{lang.icon}</span>
                <span>{lang.name.split(' ')[0]}</span>
              </button>
            );
          })}
        </div>

        {/* Main Tab Navigation */}
        <div className="flex items-center justify-around px-4 border-b border-zinc-800 bg-zinc-900/40 text-xs font-semibold">
          {[
            { id: 'templates', label: 'Code Library & Templates', icon: FileCode },
            { id: 'sandbox', label: 'Interactive Sandbox & Runner', icon: Play },
            { id: 'explainer', label: 'Code Explainer & Big-O', icon: Cpu },
            { id: 'generator', label: 'AI Code Generator', icon: Sparkles },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-2 py-3 px-3 border-b-2 font-medium transition-all ${
                  isActive
                    ? 'border-cyan-400 text-cyan-400 font-bold'
                    : 'border-transparent text-zinc-400 hover:text-zinc-200'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-6">
          {/* TAB 1: CODE TEMPLATES */}
          {activeTab === 'templates' && (
            <div className="grid grid-cols-1 md:grid-cols-12 gap-5">
              {/* Left Column: Template List */}
              <div className="md:col-span-5 space-y-3">
                <div className="relative">
                  <Search className="w-4 h-4 text-zinc-400 absolute left-3 top-2.5" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search templates, hooks, SQL..."
                    className="w-full pl-9 pr-3 py-2 rounded-xl bg-zinc-900 border border-zinc-800 text-xs text-white placeholder-zinc-500 focus:outline-none focus:border-cyan-500"
                  />
                </div>

                <div className="space-y-2 max-h-[460px] overflow-y-auto pr-1">
                  {filteredTemplates.map((template) => {
                    const isSelected = selectedTemplate.id === template.id;
                    return (
                      <div
                        key={template.id}
                        onClick={() => {
                          setSelectedTemplate(template);
                          setSandboxCode(template.codeSnippet);
                        }}
                        className={`p-3 rounded-xl border cursor-pointer transition-all ${
                          isSelected
                            ? 'bg-cyan-500/10 border-cyan-500/50 text-cyan-200 shadow-md'
                            : 'bg-zinc-900/50 border-zinc-800 text-zinc-300 hover:border-zinc-700 hover:bg-zinc-900'
                        }`}
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-zinc-800 text-cyan-400 font-bold">
                            {template.language}
                          </span>
                          <span className="text-[10px] text-zinc-400 capitalize">{template.category}</span>
                        </div>
                        <h4 className="text-xs font-bold text-white line-clamp-1">{template.title}</h4>
                        <p className="text-[11px] text-zinc-400 line-clamp-1 mt-0.5">{template.description}</p>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Right Column: Code Viewer */}
              <div className="md:col-span-7 space-y-4 bg-zinc-900/40 p-4 rounded-xl border border-zinc-800/80">
                <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
                  <div>
                    <h3 className="text-sm font-bold text-white">{selectedTemplate.title}</h3>
                    <p className="text-xs text-zinc-400 mt-0.5">{selectedTemplate.explanation}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleCopy(selectedTemplate.codeSnippet)}
                      className="px-3 py-1.5 rounded-lg bg-zinc-800 text-zinc-200 hover:text-white text-xs font-semibold flex items-center gap-1.5 border border-zinc-700"
                    >
                      {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedCode ? 'Copied' : 'Copy'}</span>
                    </button>
                    <button
                      onClick={() => {
                        setSandboxCode(selectedTemplate.codeSnippet);
                        setActiveTab('sandbox');
                      }}
                      className="px-3 py-1.5 rounded-lg bg-cyan-500 text-black text-xs font-bold flex items-center gap-1.5 hover:bg-cyan-400 shadow-md"
                    >
                      <Play className="w-3.5 h-3.5" />
                      <span>Run Sandbox</span>
                    </button>
                  </div>
                </div>

                {/* Code Block Container */}
                <div className="relative rounded-xl overflow-hidden border border-zinc-800 bg-black/80">
                  <div className="flex items-center justify-between px-4 py-2 bg-zinc-900/90 border-b border-zinc-800 text-[11px] font-mono text-zinc-400">
                    <span>{selectedTemplate.title.replace(/\s+/g, '_').toLowerCase()}.{selectedTemplate.language === 'python' ? 'py' : selectedTemplate.language === 'sql' ? 'sql' : 'ts'}</span>
                    <span className="uppercase text-cyan-400 font-bold">{selectedTemplate.language}</span>
                  </div>
                  <pre className="p-4 text-xs font-mono text-cyan-300 overflow-x-auto max-h-[340px] leading-relaxed">
                    <code>{selectedTemplate.codeSnippet}</code>
                  </pre>
                </div>

                {/* Tags */}
                <div className="flex items-center gap-2">
                  <span className="text-[10px] uppercase font-bold text-zinc-400">Tags:</span>
                  {selectedTemplate.tags.map((tag, idx) => (
                    <span key={idx} className="px-2 py-0.5 rounded-md bg-zinc-800 text-zinc-300 text-[10px] font-mono">
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: INTERACTIVE SANDBOX & RUNNER */}
          {activeTab === 'sandbox' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Terminal className="w-4 h-4 text-cyan-400" />
                  <span className="text-xs font-bold text-white uppercase tracking-wider">
                    Interactive {selectedLanguage.toUpperCase()} Runner
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleCopy(sandboxCode)}
                    className="px-3 py-1.5 rounded-lg bg-zinc-800 text-zinc-300 hover:text-white text-xs font-semibold flex items-center gap-1.5 border border-zinc-700"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Code</span>
                  </button>
                  <button
                    onClick={handleRunSandbox}
                    disabled={isExecuting}
                    className="px-4 py-1.5 rounded-lg bg-cyan-500 text-black text-xs font-bold flex items-center gap-1.5 hover:bg-cyan-400 shadow-md shadow-cyan-500/20"
                  >
                    <Play className="w-3.5 h-3.5" />
                    <span>{isExecuting ? 'Running...' : 'Execute Snippet'}</span>
                  </button>
                </div>
              </div>

              {/* Code Editor Area */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="rounded-xl border border-zinc-800 bg-black/90 flex flex-col h-[380px] overflow-hidden">
                  <div className="px-3 py-1.5 bg-zinc-900 border-b border-zinc-800 text-[11px] font-mono text-zinc-400 flex items-center justify-between">
                    <span>Editor (Editable)</span>
                    <span className="text-cyan-400 font-bold uppercase">{selectedLanguage}</span>
                  </div>
                  <textarea
                    value={sandboxCode}
                    onChange={(e) => setSandboxCode(e.target.value)}
                    className="flex-1 p-3.5 font-mono text-xs text-cyan-300 bg-transparent resize-none focus:outline-none leading-relaxed"
                    spellCheck={false}
                  />
                </div>

                {/* Console Output Window */}
                <div className="rounded-xl border border-zinc-800 bg-black/90 flex flex-col h-[380px] overflow-hidden">
                  <div className="px-3 py-1.5 bg-zinc-900 border-b border-zinc-800 text-[11px] font-mono text-zinc-400 flex items-center justify-between">
                    <span>Console Output & Telemetry</span>
                    <span className="text-emerald-400 font-bold">STATUS: OK</span>
                  </div>
                  <pre className="flex-1 p-3.5 font-mono text-xs text-emerald-400 overflow-y-auto whitespace-pre-wrap leading-relaxed">
                    {sandboxOutput}
                  </pre>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: CODE EXPLAINER & BIG-O */}
          {activeTab === 'explainer' && (
            <div className="space-y-5">
              <div className="p-4 rounded-xl bg-zinc-900/70 border border-zinc-800 space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold uppercase tracking-wider text-zinc-400 block">
                    Paste Any Code to Generate Instant Step-by-Step Breakdown & Big-O Complexity
                  </label>
                  <button
                    onClick={handleExplainCode}
                    className="px-4 py-1.5 rounded-xl bg-cyan-500 text-black font-bold text-xs hover:bg-cyan-400 transition-all flex items-center gap-1.5 shadow-md"
                  >
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Explain Logic</span>
                  </button>
                </div>
                <textarea
                  value={explainerInput}
                  onChange={(e) => setExplainerInput(e.target.value)}
                  rows={6}
                  placeholder="Paste your function or algorithm here..."
                  className="w-full p-3 rounded-xl bg-black/70 border border-zinc-700 text-xs font-mono text-cyan-300 focus:outline-none focus:border-cyan-500"
                />
              </div>

              {explanationReport && (
                <div className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800 space-y-4">
                  <div className="flex items-center justify-between pb-3 border-b border-zinc-800">
                    <div>
                      <h4 className="text-sm font-bold text-white">{explanationReport.title}</h4>
                      <p className="text-xs text-zinc-400">{explanationReport.summary}</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="px-2.5 py-1 rounded-md bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono font-bold">
                        Time: {explanationReport.timeComplexity}
                      </span>
                    </div>
                  </div>

                  {/* Line by line breakdown */}
                  <div className="space-y-2.5">
                    <h5 className="text-xs font-bold uppercase tracking-wider text-zinc-400">
                      Step-by-Step Execution Logic
                    </h5>
                    {explanationReport.lineByLineExplanation.map((line, idx) => (
                      <div key={idx} className="p-3 rounded-xl bg-zinc-900 border border-zinc-800 text-xs space-y-1">
                        <pre className="font-mono text-[11px] text-cyan-300 line-clamp-2 bg-black/40 p-1.5 rounded">
                          <code>{line.lines}</code>
                        </pre>
                        <p className="text-zinc-300 text-xs">{line.explanation}</p>
                      </div>
                    ))}
                  </div>

                  {/* Best Practices */}
                  <div className="p-3.5 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-xs text-cyan-200 space-y-1.5">
                    <span className="font-bold text-cyan-300">Engineering Best Practices:</span>
                    <ul className="list-disc list-inside space-y-1 text-zinc-300">
                      {explanationReport.bestPractices.map((bp, idx) => (
                        <li key={idx}>{bp}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 4: AI CODE GENERATOR */}
          {activeTab === 'generator' && (
            <div className="space-y-5">
              <div className="p-4 rounded-xl bg-zinc-900/70 border border-zinc-800 space-y-3">
                <label className="text-xs font-bold uppercase tracking-wider text-zinc-400 block">
                  Describe the Feature, Component, Hook, or Script You Need
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={generatorPrompt}
                    onChange={(e) => setGeneratorPrompt(e.target.value)}
                    placeholder="e.g. 'Build an express rate limiter middleware with Redis' or 'React custom hook for audio streaming'..."
                    className="flex-1 px-4 py-2.5 rounded-xl bg-black/60 border border-zinc-700 text-xs text-white placeholder-zinc-500 focus:outline-none focus:border-cyan-500"
                  />
                  <button
                    onClick={handleGenerateCode}
                    className="px-5 py-2.5 rounded-xl bg-cyan-500 text-black font-bold text-xs hover:bg-cyan-400 transition-all flex items-center gap-2 shadow-lg shadow-cyan-500/20"
                  >
                    <Sparkles className="w-4 h-4" />
                    <span>Generate Code</span>
                  </button>
                </div>
              </div>

              {generatedCode && (
                <div className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800 space-y-3">
                  <div className="flex items-center justify-between pb-2 border-b border-zinc-800">
                    <span className="text-xs font-bold text-cyan-400 font-mono">Generated TypeScript Solution</span>
                    <button
                      onClick={() => handleCopy(generatedCode)}
                      className="px-3 py-1.5 rounded-lg bg-zinc-800 text-zinc-200 text-xs font-semibold flex items-center gap-1.5 hover:bg-zinc-700"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Solution</span>
                    </button>
                  </div>
                  <pre className="p-4 rounded-xl bg-black/80 border border-zinc-800 text-xs font-mono text-cyan-300 overflow-x-auto max-h-[360px] leading-relaxed">
                    <code>{generatedCode}</code>
                  </pre>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-3 border-t border-zinc-800 bg-zinc-900/60 text-xs text-zinc-400">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse"></span>
            <span>AI Code Engine: Multi-language AST parser ready</span>
          </div>
          <span className="text-zinc-500 font-mono">TypeScript • Python • SQL • React 18+</span>
        </div>
      </div>
    </div>
  );
};
